# Generated by Django 3.0.4 on 2020-04-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_name', models.CharField(max_length=200, verbose_name='Предположительный вид растения')),
                ('photo_file', models.ImageField(upload_to='', verbose_name='Изображение предпологаемого вида')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoInDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_name', models.CharField(max_length=50, verbose_name='Имя фотографии')),
                ('photo_author', models.CharField(max_length=50, verbose_name='Автор фотографии')),
                ('photo_group', models.CharField(max_length=20, verbose_name='Группа изображения')),
                ('photo_date', models.DateTimeField(verbose_name='Дата загрузки фото')),
                ('photo_file', models.ImageField(upload_to='media/img', verbose_name='Файл изображения')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_name', models.CharField(max_length=50, verbose_name='Имя фотографии')),
                ('photo_date', models.DateTimeField(verbose_name='Дата загрузки фото')),
                ('photo_file', models.ImageField(upload_to='requests/', verbose_name='Файл изображения')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoToDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_name', models.CharField(default='', max_length=60, verbose_name='Имя фотографии')),
                ('photo_author', models.CharField(max_length=50, verbose_name='Автор фотографии')),
                ('photo_group', models.CharField(max_length=20, verbose_name='Вид растения')),
                ('photo_author_ip', models.GenericIPAddressField(default='0.0.0.0', verbose_name='ip адресс автора')),
                ('photo_date', models.DateTimeField(default='2020-01-01 00:00:00', verbose_name='Дата и время загрузки фото')),
                ('photo_file', models.ImageField(upload_to='img_to_database/', verbose_name='Файл изображения')),
            ],
        ),
    ]
