# Generated by Django 3.0.6 on 2020-06-25 19:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_field', models.CharField(max_length=30, verbose_name='Login')),
                ('password_field', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254, verbose_name='Емаил пользователя')),
                ('theme_field', models.CharField(max_length=150, verbose_name='Тема')),
                ('message_field', models.TextField(max_length=500, verbose_name='Сообщение')),
                ('author_ip', models.GenericIPAddressField(default='0.0.0.0', verbose_name='ip адресс пользователя')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_name', models.CharField(default='', max_length=50, verbose_name='Имя фотографии')),
                ('photo_date', models.DateTimeField(default=datetime.datetime(2020, 6, 25, 22, 1, 18, 765229), verbose_name='Дата загрузки фото')),
                ('photo_file', models.ImageField(upload_to='requests/', verbose_name='Файл изображения')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoToDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_name', models.CharField(default='', max_length=60, verbose_name='Имя фотографии')),
                ('photo_author', models.CharField(max_length=50, verbose_name='Автор фотографии')),
                ('photo_group', models.CharField(max_length=20, verbose_name='Вид растения')),
                ('photo_author_ip', models.GenericIPAddressField(default='0.0.0.0', verbose_name='ip адресс автора')),
                ('photo_date', models.DateTimeField(default='1111-11-11 11:11:11', max_length=25, verbose_name='Дата и время загрузки фото')),
                ('photo_file', models.ImageField(upload_to='img_to_database/', verbose_name='Файл изображения')),
            ],
        ),
    ]
