# Generated by Django 3.0.4 on 2020-04-06 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuralmain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photorequest',
            name='photo_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 6, 17, 57, 9, 262701), verbose_name='Дата загрузки фото'),
        ),
        migrations.AlterField(
            model_name='photorequest',
            name='photo_name',
            field=models.CharField(default='', max_length=50, verbose_name='Имя фотографии'),
        ),
        migrations.AlterField(
            model_name='phototodatabase',
            name='photo_date',
            field=models.CharField(default='2020-04-06 17:57:09', max_length=25, verbose_name='Дата и время загрузки фото'),
        ),
    ]
