# Generated by Django 3.0.6 on 2020-07-03 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuralmain', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auth',
            name='access_field',
        ),
        migrations.AlterField(
            model_name='photorequest',
            name='photo_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 3, 11, 13, 53, 683545), verbose_name='Дата загрузки фото'),
        ),
    ]
