# Generated by Django 3.0.4 on 2020-04-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuralmain', '0002_auto_20200401_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phototodatabase',
            name='photo_file',
            field=models.ImageField(upload_to='img_to_database/<django.db.models.fields.CharField>', verbose_name='Файл изображения'),
        ),
    ]
