# Generated by Django 3.0.4 on 2020-04-06 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuralmain', '0002_auto_20200406_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photorequest',
            name='photo_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 6, 18, 3, 46, 172348), verbose_name='Дата загрузки фото'),
        ),
        migrations.AlterField(
            model_name='phototodatabase',
            name='photo_date',
            field=models.DateTimeField(default='1111-11-11 11:11:11', max_length=25, verbose_name='Дата и время загрузки фото'),
        ),
    ]
