# Generated by Django 3.0.4 on 2020-04-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuralmain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_name', models.CharField(max_length=50, verbose_name='Имя фотографии')),
                ('photo_date', models.DateTimeField(verbose_name='Дата загрузки фото')),
                ('photo_file', models.ImageField(upload_to='requests/', verbose_name='Файл изображения')),
            ],
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.AlterField(
            model_name='phototodatabase',
            name='photo_file',
            field=models.ImageField(upload_to='img_to_database/', verbose_name='Файл изображения'),
        ),
    ]
