# Generated by Django 3.0.4 on 2020-04-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuralmain', '0003_auto_20200401_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phototodatabase',
            name='photo_author_ip',
            field=models.GenericIPAddressField(null=True, verbose_name='ip адресс автора'),
        ),
        migrations.AlterField(
            model_name='phototodatabase',
            name='photo_date',
            field=models.DateTimeField(null=True, verbose_name='Дата и время загрузки фото'),
        ),
        migrations.AlterField(
            model_name='phototodatabase',
            name='photo_file',
            field=models.ImageField(upload_to='img_to_database/', verbose_name='Файл изображения'),
        ),
        migrations.AlterField(
            model_name='phototodatabase',
            name='photo_group',
            field=models.CharField(max_length=20, verbose_name='Вид растения'),
        ),
        migrations.AlterField(
            model_name='phototodatabase',
            name='photo_name',
            field=models.CharField(max_length=60, null=True, verbose_name='Имя фотографии'),
        ),
    ]
