# Generated by Django 3.0.4 on 2020-04-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuralmain', '0004_auto_20200403_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phototodatabase',
            name='photo_author_ip',
            field=models.GenericIPAddressField(default='0.0.0.0', verbose_name='ip адресс автора'),
        ),
        migrations.AlterField(
            model_name='phototodatabase',
            name='photo_date',
            field=models.DateTimeField(default='2020.01.01 00:00:00', verbose_name='Дата и время загрузки фото'),
        ),
        migrations.AlterField(
            model_name='phototodatabase',
            name='photo_name',
            field=models.CharField(default='byMechanoid', max_length=60, verbose_name='Имя фотографии'),
        ),
    ]
