# Generated by Django 3.0.4 on 2020-04-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuralmain', '0005_auto_20200403_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phototodatabase',
            name='photo_date',
            field=models.DateTimeField(default='2020-01-01 00:00:00', verbose_name='Дата и время загрузки фото'),
        ),
    ]
