# Generated by Django 3.0.4 on 2020-04-03 12:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuralmain', '0006_auto_20200403_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phototodatabase',
            name='photo_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 3, 15, 21, 51, 810724), verbose_name='Дата и время загрузки фото'),
        ),
    ]
