# Generated by Django 3.0.4 on 2020-04-03 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neuralmain', '0007_auto_20200403_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phototodatabase',
            name='photo_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата и время загрузки фото'),
        ),
    ]
